name: Feature Request
description: Suggest improvements to the APP
title: "[Enhancement]: "
labels: ["enhancement🚀"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to make a feature request, please fill in the following information after completing the title.
        
        歡迎提出功能建議，請先填寫完整標題，再補充以下資訊。
        
        **Please do not report config-file/comic-source script issues in this repository.**

        **請不要在此儲存庫回報 config/comic source 腳本相關問題。**

        This project is a comic reader that allows users to write their own config files, and there is no built-in comic source.

        本專案是漫畫閱讀器，允許使用者自行撰寫設定檔，且沒有內建漫畫來源。

        Config / comic source issues should be reported to:
        https://github.com/venera-app/venera-configs/issues
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe your suggestion.
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Operating System
      description: If the feature is for a particular platform, please select here
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - macOS
        - linux
        - other
    validations:
      required: false
  - type: textarea
    id: screenshotOrVideo
    attributes:
      label: picture
      description: If you need to use a picture, please upload it here.
