name: "analyze"
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: analyze-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v1
